name: Symfony

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    steps:
      # 1. On télécharge le code du projet en tout premier
      - uses: actions/checkout@v5

      # 2. Ensuite on installe PHP
      - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
        with:
          php-version: '8.0' # (Vérifiez que votre composer.json accepte bien la version 8.0)
      - run: ls
      # 3. On prépare le fichier .env
      - name: Copy .env.test.local
        run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"

      # 4. On gère le cache Composer
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      # 5. Enfin, on installe les dépendances (le composer.json est désormais présent)
      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      # 6. Création de la base de données SQLite
      - name: Create Database
        run: |
          mkdir -p data
          touch data/database.sqlite

      # 7. Exécution des tests PHPUnit
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DATABASE_URL: sqlite:///%kernel.project_dir%/data/database.sqlite
        run: vendor/bin/phpunit
